version: '3.8'
services:
  app:
    image: nazmulhasn/skysync_backend:latest
    container_name: skysync_backend
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=skysync_redis
      - REDIS_PORT=6379
    ports:
      - '5000:5000'
      - '5005:5005'
    depends_on:
      - mongo
      - redis
    expose:
      - 5000
      - 5005
